<a href="https://colab.research.google.com/github/dequiroz/1MTR53_RobIA/blob/main/1MTR53_Guia_Python_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Introducción de Python

##¿Que es Python?
Python es uno de los lenguajes de programación más empleados en el ámbito de la robótica e inteligencia artificial.
Se define como *un lenguaje de programación interpretado, orientado a objetos, de alto nivel y con semántica dinámica*. Esto implica lo siguiente:
- **Interpredato**: Implica que el lenguaje no es compilado. Es decir, un código de python se puede ejecutar de forma directa. Esto también implica que errores no son detectados hasta el tiempo de ejecución (run-time).
- **Orientado a objetos**: Todo en python se representa por objetos, por lo que pueden usar clases y métodos. Esto permite emplear una estructura ordenada y lógica al momento de programar.
- **Alto nivel**: Permite programar empleando palabras "comunes", logrando tener un programa funcional en poco tiempo y sin mucha complejidad.
- **Semantica dinámica**: Implica que las variables son objetos, por lo que no es necesario especificar el tipo de dato. Python puede determinar esa información.

In [ ]:
#Ejemplo de semantica dinámica
x = 5   #Python reconoce que x contiene un valor numerico
x = x - 2 #La clase INT permite realizar operaciones matematicas
print(f'{x=}')
x = 'Hola' #Python reconoce que x ahora contiene una cadena
x = x.upper() #el metodo upper pertenece a la clase string y se usa para cambiar una cadena a mayusculas
print(f'{x=}')

x=3
x='HOLA'


# 2. Conceptos básicos

##Variables:
Un programa está compuesto por instrucciones que operan sobre información. Esta información se almacena en celdas de memoria llamadas variables a las que se accede a través de un nombre.

En Python el nombre de una variable puede contener letras, cifras, y símbolos unicode, **pero no
puede comenzar por un número, ni contener operadores, ni ser una palabra reservada del
lenguaje de programación.**

Por ejemplo: i , año , x1, dni_alumno.

##Tipos de datos:
La información almacenada en variables y procesada por instrucciones puede ser de varios tipos.
En Python estos son:
- int : 5 , 0x10 , 0b10 , 123123123123123123123123123123123123123123123123
- float : 0.5 , 0.5e7 , 1.79e308 , 1.8e308 , -1.8e308 , 5e-324 , 1e-325
- complex : 0.5 + 2j
- boolean : True / False
- string : 'hola mon' , "hola mon" , '' , 'hola\tadeu\n'
- lista : ['dll', 'dm', 'x', 'dj', 'dv', 'dss', 'dg']
- tupla : ('dll', 'dm', 'x', 'dj', 'dv', 'dss', 'dg')
- diccionario : {'Ana':20, 'Bob':40, 'Pep':30}




##Comentarios:
Los comentarios son un texto que añadimos al programa y que, a diferencia de las instrucciones, no se ejecuta. Su propósito es aportar información a las personas que lean el código fuente del programa.

En Python tenemos comentarios de una línea:

    instrucción # comentario


##Operadores:
- aritméticos: + , - , * , / , // , % , **
- lógicos: < , <= , > , >= , == , != , and , or , not.

  Utilizar paréntesis para agrupar operaciones.

##Funciones matemáticas:
Se debe importar la librería math. Escribir a inicio del programa, como primera línea:

    import math

 math.abs() , math.sin() , math.log() , math.sqrt() , math.pi, etc.


##Conversión entre tipos de datos:
- a entero (tipo de datos “int”): int('25') , int(25.9) , round(25.9)
- a real (tipo de datos “float”): float('25.5') , float(25)
- a cadena (tipo de datos “string”): str(25.5)

##Entrada por teclado:
Se asigna el valor ingresado a la variable declarada

    variable = input('texto a imprimir')

Por ejemplo:

    nombre = input('¿Cómo te llamas? ')
    edad = int( input('¿Cuántos años tienes? ') )
    r = float( input('¿Qué mide el radio? ') )

##Salida por consola:

    print('text a imprimir', variables, ...)

Por ejemplo:

    print('Hola', nombre)
    print(a, b, c, sep='|', end=' ')
    print('resultado','\t',3*5,'\n')
    print('''
    Este texto
    ocupa varias líneas
    ''')
    print('El nombre es %s y la edad %d años' % (nombre, edad))
    print(f'El nombre es {nombre} y la edad {edad} años')
    print(f'Área: {(PI*r*r):7.2f}')



In [ ]:
a = 2 #asignación de variable a
b = 4 #asignación de variable b

#imprimir el resultado de operaciones matemáticas
print(a+b)
print(a*b)
print(a**b)
print(b/a)


6
8
16
2.0


In [ ]:
print('Suma de dos enteros')
#solicita ingreso de numeros por teclado
a = int( input('Entre el dato 1: ') )
b = int( input('Entre el dato 2: ') )
#realiza operación entre dos numeros
suma = a + b
print('La suma vale:' , suma)




Suma de dos enteros
Entre el dato 1: 7
Entre el dato 2: 3
La suma vale: 10


# 3. F-Strings
Este tipo de cadenas son bastante usadas en python para simplificar o dar formato a una variable a imprimir. Se definen colocando el caracter f previo a las comillas de la cadena.

`f'hola'`

Este tipo de cadenas puede contener llaves {}, dentro de las cuales se puede indicar codigo que se desea ejecutar previo a la definicion de la cadena. Esto permite obtener cadenas **dinamicas**

Adicionalmente, se puede dar formato a las variables con el caracter **:**

In [ ]:
x = 10
print(f'se tiene {x} manzanas')
print(f'se tiene {x-2} manzanas')
print(f'se tiene {x:.2f} manzanas') #formato de numero flotante con 2 decimales
print(f'se tiene {x**6:,} manzanas') #Usar , como separador de numeros

se tiene 10 manzanas
se tiene 8 manzanas
se tiene 10.00 manzanas
se tiene 1,000,000 manzanas


f-string tambien permite debugear de forma sencilla empeando el caracter **=**
Notas en los siguientes ejemplos, que el espacio al rededor del = se mantiene, permitiendo mantener una lectura adecuada

In [ ]:
x = 100
print(f'{x = }')
y = 'un valor'
print(f'{y= }')
z = [1,2,3]
print(f'{z=}')

x = 100
y= 'un valor'
z=[1, 2, 3]


#4. Condicionales
Las comparaciones se pueden unir mediante operadores lógicos para formar expresiones lógicas
más complejas. Dichos conectores lógicos son: and (y) , or (o), not (no).

Instrucción condicional if … :

    if condición:
      instrucciones

Instrucción condicional if … else … :

    if condición:
      instrucciones
    else:
      instrucciones

Instrucción condicional if … elif …elif… else … :

    if condición:
      instrucciones
    elif condición:
      instrucciones
    ...
    else:
      instrucciones

Gestión de excepciones:

    try:
      instrucciones
    except excepción:
      instrucciones
    ...
    finally:
      instrucciones


In [ ]:
nota = int(input('¿Ingrese la calificación? '))
if (nota < 0) or (nota > 20):
  print('Nota incorrecta')
elif nota >= 11:
  print('Aprobado:', nota)
else:
  print('Desaprobado:', nota)


¿Ingrese la calificación? f


ValueError: invalid literal for int() with base 10: 'f'

In [ ]:
try:
 edad = int(input('¿Cuantos años tienes? '))
 print('Cumplirás', edad+1)
except ValueError:
 print('¡Oops! No era un valor correcto')
finally:
 print('Adios')


¿Cuantos años tienes? g
¡Oops! No era un valor correcto
Adios


#5.Iteración

Instrucción iterativa de condición inicial while … :

    while condición:
      instrucciones

Instrucción iterativa repetitiva for … :

    for variable in lista / string / range(inicio, final, incremento):
      instrucciones

Instrucción break finaliza bucles:
Con esta instrucción se puede salir inmediatamente del bucle while o for que se estaba ejecutando.
El siguiente ejemplo escribe “s t r Adios”:

    for val in 'string':
      if val == 'i':
        break # Finaliza las iteraciones
      print(val)
    print('Adios')

Instrucción continue que finaliza iteraciones:
Con esta instrucción se puede salir inmediatamente de la actual iteración del bucle while o for para pasar a
la siguiente. El siguiente ejemplo escribe “s t r n g Adios”:

    for val in 'string':
      if val == 'i':
        continue # Se va a la siguiente iteración sin acabar esta
      print(val)
    print('Adios')

In [ ]:
print('Cálculo de la media de una serie de datos');
print('-----------------------------------------');
# Inicializamos las variables
suma = 0
num = 0
# Leemos datos y los procesamos hasta que introducen 0
x = float( input('Introduce un valor (0 para acabar) : ') )
while x != 0:
 suma = suma + x
 num = num + 1
 x = float( input('Introduce un valor (0 para acabar) : ') )
# Damos los resultados
print('La media de los elementos es', suma/num)

Cálculo de la media de una serie de datos
-----------------------------------------
Introduce un valor (0 para acabar) : 3
Introduce un valor (0 para acabar) : 4
Introduce un valor (0 para acabar) : 5
Introduce un valor (0 para acabar) : 0
La media de los elementos es 4.0


In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
for i in range(2,5):
  print(i)

2
3
4


In [ ]:
for i in range(2,5,2):
  print(i)

2
4


In [ ]:
for value in [1,2,9]:
  print(value)

1
2
9


#6. Estructuras de almacenamiento
¿Qué es una lista?

Una variable de tipo lista es capaz de almacenar una secuencia de valores simultáneamente.

Por ejemplo:

    l = [1, 3, -0.5, True, 'Patata']

A cada uno de dichos valores se puede acceder como si fuera una variable independiente, a través de un índice que indica su posición: 0, 1, 2, 3, … . Por ejemplo:

    print( l[2] )
    l[0] = l[0] + 1

Adicionalmente se pueden obtener sublistas emplando rangos de indices

```
lista = [0,1,2,3,4]
print(lista[2:])
print(lista[2:4])
print(lista[-2:])
print(lista[:-2])
```



En python una lista esta compuesta por objetos, por lo que una lista puede estar formada por elementos de diferentes tipos de datos (“heterogéneo”)

vectores o arreglos "clásicos" (de un mismo tipo de datos) se pueden realizar con la libreria numpy.array

Las tuplas son listas que no se puede modificar su contenido. La diferencia es que en lugar de delimitarlas con corchetes [] se
delimitan con paréntesis (). Por ejemplo:

    t = (1, 3, -0.5, True, 'Patata')
    print( t[2] )
    t[0] = t[0] + 1 # ERROR: una tupla no se puede modificar

Los diccionario son un conjunto de valores a los que no accedemos por índice sino por clave. Sintácticamente, la diferencia es que en lugar de delimitarlas con corchete "[ ]" se delimitan con llaves "{ }", y se precede cada elemento con la clave para acceder a él. Por ejemplo:

    agenda = {'Ana':644343434, 'Edu':622121243, 'Bob':679444444}
    print( agenda['Edu'] )
    agenda['Pep'] = 686252554


    

In [ ]:
a = [0, 0]
b = [0, 0, 0]
a[0] = 2
a[1] = a[0] ** a[0] #** implica potencia
a.append( a[0] + a[1] +10) #Agrega un nuevo elemento al final de la lista
b[1 + 1] = a[0] - 1
b[a[0]-1] = 2*a[1] - 1
b[2*a[0]-a[1]] = b[0] + 1
for i in range(0,3):
  b[i] = b[i] + i

print(a)
print(b)

[2, 4, 16]
[1, 8, 3]


In [10]:
lista = [1, 2, 3, 4, 5]

#lista2 = [1, 4, 9, 16, 25]

lista2 = []

for elemento in lista:
  if elemento % 2 == 0:
    cuadrado = elemento ** 2
    lista2.append(cuadrado)

print(f'{lista2 = }')

lista3 = [elemento ** 2 for elemento in lista if elemento % 2 == 0]
[valores_a_almacenar | bucle | selectiva]

print(f'{lista3 = }')

lista2 = [4, 16]
lista3 = [4, 16]


In [35]:
lista1 = ['a', 'b', 'c', 'd', 'e']
lista2 = [15, 20, 25]

for sensor1, sensor2 in zip(lista, lista2):
  print(f'{sensor1 = }' )
  print(f'{sensor2 = }' )
  print()
  #sensor1 = lista1[i]
  #sensor2 = lista2[i]
  #sensor3 = lista3[i]

#print()

#for i in range(5):
  #print(i, comandos[i])

sensor1 = 'a'
sensor2 = 15

sensor1 = 'b'
sensor2 = 20

sensor1 = 'c'
sensor2 = 25



# 7. Comprension de listas (List Comprehension)
Este es un concepto de python que permite generar y trabajar con listas de forma facil.
Debido a que python es un lenjuage interpretado, se puede emplear un codigo iterable en la definición de una lista para generar su valor inicial. Por ejemplo, un bucle tipo for.

En el siguiente ejemplo se usa un for y se indica que los valores que toma la variable i (de 0 a 4) se empleen para generar la lista

In [ ]:
a = [i for i in range(5)]
print(a)

[0, 1, 2, 3, 4]


Otra forma de emplear el concepto es para simplificar código que genera listas según operaciones externas, como en el siguiente ejemplo donde se genera una lista **b** mediante un bucle en el cual se itera de forma independiente por cada item de la lista data y se almacena el valor redondeado.
Por otro lado, la lista **c** se genera mediante una conprensión, resultando en el mismo valor

In [ ]:
data = [100.23, 97.68, 45.07]

b = []
for value in data:
  b.append(round(value))

c = [round(value) for value in data]

print(b)
print(c)

[100, 98, 45]
[100, 98, 45]


Comprensiones de listas permiten tambien colocar condicionales para definir que valores son partes de la nueva lista.

In [ ]:
a = [1, 15, 20, 40, 6, 34, 100]
b = [item for item in a if item > 30]
print(f'{b = }')

b = [40, 34, 100]


In [47]:
lista1 = [1,2,3,4,5]
lista2 = lista1.copy()

print(f'{lista1 = }')
print(f'{lista2 = }')

lista1[0] = 10

print(f'{lista1 = }')
print(f'{lista2 = }')



lista1 = [1, 2, 3, 4, 5]
lista2 = [1, 2, 3, 4, 5]
lista1 = [10, 2, 3, 4, 5]
lista2 = [1, 2, 3, 4, 5]


#8. Funciones

Una función puede recibir y devolver cualquier tipo de dato.
Ejemplos:

    def suma(a, b):
      return a + b

    def resta(a, b):
      return a - b

    def multiplica(a, b):
      return a * b

    def divide(a, b):
      return a / b
      
    edad = suma(30, 5)
    alto = resta(78, 4)
    peso = multiplica(90, 2)
    iq = divide(100, 2)
    print(f'Age: {edad}, Height: {alto}, Weight: {peso}, IQ: {iq}')
    total = suma(edad, resta(alto, multiplica(peso, divide(iq, 2))))
    print('Eso es: ', total)




In [48]:
def suma(a, b):
  return a + b

def resta(a, b):
  return a - b

def multiplica(a, b):
  return a * b

def divide(a, b):
  return a / b

edad = suma(30, 5)
alto = resta(78, 4)
peso = multiplica(90, 2)
iq = divide(100, 2)
print(f'Edad: {edad}, Tamaño: {alto}, Peso: {peso}, IQ: {iq}')
total = suma(edad, resta(alto, multiplica(peso, divide(iq, 2))))
print('Eso es: ', total)

Edad: 35, Tamaño: 74, Peso: 180, IQ: 50.0
Eso es:  -4391.0


In [75]:
'''
no
 es
 un
 comentario
 multilinea
'''

def mover_robot(direccion, distancia=3, velocidad=1):
  '''
  DOCSTRING: Documentacion para una funcion o clase
  explicacion de los parametros de entrada
  que operacion realiza
  que valores devuelve
  '''
  #calcular cinematica
  #enviar señales a motores
  #medir distancia recorrida
  #Corregir movimiento si no se ha despalzado la distancia solicitada
  print(f'El robot se desplazo en direccion {direccion} {distancia} metros a {velocidad} m/s')


mover_robot(direccion='al frente', velocidad=2)


def operaciones(a, b):
  suma = a+b
  diferencia = a-b
  producto = a*b
  dividendo = a/b
  return suma, diferencia, producto, dividendo

suma, *_, divi = operaciones(10, 5)

print(f'{suma = }')
#print(f'{dif = }')
print(f'{_ = }')
print(f'{divi = }')


El robot se desplazo en direccion al frente 3 metros a 2 m/s
suma = 15
_ = [5, 50]
divi = 2.0


Parámetros variables:

En caso que a una función deba recibir un número indeterminado y variable de parámetros, en Python podemos declarar con * que el número los parámetros es
variable, y en ese caso los argumentos serán recibidos en una tupla (una lista inmutable).
Por ejemplo:


In [ ]:
def imprimir(*args):
  print('la funcion tiene: ', len(args), 'argumentos')
  for a in args:
    print(' argumento:', a)

imprimir(3, 'hola')
imprimir('fresa', [1, 2], True)




la funcion tiene:  2 argumentos
 argumento: 3
 argumento: hola
la funcion tiene:  3 argumentos
 argumento: fresa
 argumento: [1, 2]
 argumento: True


#9. Datos Mutables e Inmutables

**Es importante poder diferenciar entre variables mutables e inmutables**: La primera implica que son variables cuyo valor puede ser modificado, mientras que la segunda son variable cuyo valor queda definido al momento de asignarles un valor y no se puede ser modificado a menos de que se vuelva a reasignar
Los tipos de variables inmutables son:
- str
- int
- float
- bool
- bytes
- tuple

mientras que los datos mutables son:
- list
- set
- dict

##Ejemplo 1
En el siguiente ejemplo se observa la definicion de una tubla (objeto inmutable) y el error que se genera al intentar realizar una modificacion

In [ ]:
#Ejemplo 1
# definición de una tupla
x = (1,2)
x[0] = 3 #No se puede cambiar y retorna error

TypeError: 'tuple' object does not support item assignment

##Ejemplo 2
En el siguiente ejemplo, se observa la creacion de 1 tupla cuyo valor se copia en otra variable **y**. Al ser una copia, su valor no se modifica al reasignarle valores distintos a la variable **x** original
Este es el comportamiento "esperado" segun otros lenguajes de programación

In [ ]:
#Ejemplo 2
# definición de una tupla
x = (1,2)
y = x  #Se crea una copia de forma automatica

x = (1,2,3) #Se reasigna otra tupla a la variable x

print(x,y) #Observamos que ambas variables tienen valores distintos asignados

(1, 2, 3) (1, 2)


##Ejemplo 3
Aqui se intenta hacer lo mismo que en el ejemplo anterior. Sin embargo esta vez se emplean listas (objetos mutables). Debido a ello, al realizar la asignación en la segunda linea, la variable y ahora contiene una referencia a la variable x, por lo que estas dos variable apuntan hacia el mismo objeto. Debido a ello, cualquier cambio en una de ellas se ve reflejado en la otra, como se puede observar en el resultado.

In [ ]:
#Ejemplo 3
# definición de una lista
x = [1,2]
y = x  #Se crea una REFERENCIA al objeto

x[0] = 100 #Se modifica el valor del primer indice de la lista
print(x,y)

[100, 2] [100, 2]


##Ejemplo 4
En el siguiente ejemplo se puede ver el uso de una función que retorna los N números las grandes de una lista. Sin embargo, como se están empleando objetos inmutables, se puede ver que la lista original **nums** es modificada por la función. Este comportamiento puede ser no deseado y depende del programador. Lo importante es conocer que esto puede pasar para decidir si es comportamiento deseado o no.

In [76]:
def get_largest_numbers(numbers, n):
  numbers.sort()

  return numbers[-n:]

nums = [2,3,4,1,34,123,321,1]

print(f'{nums = }')
largest = get_largest_numbers(nums, 2)
print(f'{largest = }')
print(f'{nums = }')


nums = [2, 3, 4, 1, 34, 123, 321, 1]
largest = [123, 321]
nums = [1, 1, 2, 3, 4, 34, 123, 321]


#NUMPY

NumPy (Numerical Python) es la librería base para el cálculo numérico en Python.
Proporciona estructuras de datos y operaciones optimizadas para manejar grandes volúmenes de información numérica.

* Núcleo de muchas otras librerías científicas (SciPy, OpenCV, ROS bindings).
* Basado en arreglos multidimensionales.
* Mucho más rápido que las listas nativas de Python.
* Ideal para operaciones matriciales, filtrado, álgebra lineal, transformaciones y sensores.

Para usar numpy se emplea la siguiente instrucción



```python
import numpy as np
```

np es la convención que siempre usamos para numpy.
Mantener la convención facilita compartir el código con otros desarrolladores.




## Arreglos en Numpy

Según la documentación de numpy:

“ Arreglos son una estructura para almacenar y recuperar datos.”
	numpy docs:	 https://numpy.org/doc/stable/user/absolute_beginners.html


Arreglos pueden ser de varias dimensiones

In [2]:
import numpy as np

arr1D = np.array([1, 5, 2, 0])
arr2D = np.array([[1, 5, 2, 0], [8, 3, 6, 1], [1, 7, 2, 9]])

print(f'{arr1D = }')
print()
print(f'{arr2D = }')

arr1D = array([1, 5, 2, 0])

arr2D = array([[1, 5, 2, 0],
       [8, 3, 6, 1],
       [1, 7, 2, 9]])


## Restricciones en arreglos

1. Todos los datos en un arreglo deben de ser del mismo tipo
2. La longitud de un arreglo no puede cambiar


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print(f'el arreglo contiene solo valores numericos enteros')
print(arr)

print(f'\nel arreglo contiene solo valores numericos decimales')
arr = np.array([1, 2, 3, 4, 5, 6.0])
print(arr)


print(f'\nel arreglo contiene solo caracteres')
arr = np.array([1, 2, 3, 4, 5, '6'])
print(arr)



el arreglo contiene solo valores numericos enteros
[1 2 3 4 5 6]

el arreglo contiene solo valores numericos decimales
[1. 2. 3. 4. 5. 6.]

el arreglo contiene solo caracteres
['1' '2' '3' '4' '5' '6']


3. Si se desea agregar o extender el arreglo se debe de crear uno nuevo

In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])

nuevo_arr = np.append(arr, [10,20])
print(f'{nuevo_arr = }')

nuevo_arr = array([ 1,  2,  3,  4,  5,  6, 10, 20])


4. El arreglo debe de ser rectangular

In [10]:
import numpy as np

arr = np.array([[1,2,5,4],[0,4,3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

Estas restricciones son necesarias para garantizar la velocidad y eficiencia de un numpy-array.

Listas nativas de python son flexibles, lo cual implica una pérdida de rendimiento.

## Acceso a los datos

El acceso a los datos de los arreglos es similar a listas. Se puede realizar con el índice entero en llaves []

Los arreglos no puedes cambiar su tamaño, pero son mutables, es decir podemos modificar su contenido


In [12]:
import numpy as np

lista = [1, 2, 3, 4, 5, 6]
arr = np.array(lista)


print(f'{arr = }')
print(f'{arr[2] = }')

arr[2] = 999

print(f'{arr = }')

arr = array([1, 2, 3, 4, 5, 6])
arr[2] = np.int64(3)
arr = array([  1,   2, 999,   4,   5,   6])


Al igual que listas, se puede aplicar cortes con los indices

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print(f'{arr[2:] = }')
print(f'{arr[::2] = }')
print(f'{arr[1:4] = }')

arr[2:] = array([3, 4, 5, 6])
arr[::2] = array([1, 3, 5])
arr[1:4] = array([2, 3, 4])


CUIDADO:
    Un corte de listas retorna una copia.
    En numpy retorna un “vista”

In [15]:
import numpy as np

lista = [1, 2, 3, 4, 5, 6]
arr = np.array(lista)

slice_lista = lista[:3]
slice_lista[0] = 20
print(f'{lista = }')
print(f'{slice_lista = }')


ventana1 = arr[:3]
ventana1[0] = 20
print(f'{arr = }')
print(f'{ventana1 = }')

lista = [1, 2, 3, 4, 5, 6]
slice_lista = [20, 2, 3]
arr = array([20,  2,  3,  4,  5,  6])
ventana1 = array([20,  2,  3])


##Arreglos de mayor dimension

Arreglos multidimensionales se inicializan con listas anidadas.


Para acceder a cada dato se puede usar el índice [fila, columna]


In [16]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8,9]])
print(arr2d)

#array2d[fila, columna]

print(f'{arr2d[2,1] = }')


[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[2,1] = np.int64(8)


array 0D - ESCALARES

array 1D - Vectores

array 2D - Matrices

array nD - Tensor

## Atributos de arreglos

* Obtener  dimensiones de un arreglo: ndim
* Forma de un arreglo: shape
* Tamaño de un arreglo: size
* Tipo de datos en un arreglo: dtype


In [19]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8,9], [10,11,12]], dtype=np.int8)

print(f'{arr2d.ndim = }')
print(f'{arr2d.shape = }')
print(f'{arr2d.size = }')
print(f'{arr2d.dtype = }')

arr2d.ndim = 2
arr2d.shape = (4, 3)
arr2d.size = 12
arr2d.dtype = dtype('int8')


## Métodos para creación de arreglos

In [131]:
import numpy as np

#matriz 4 x 2 con vaores iniciales zeros
print(np.zeros((4,2)))

#matriz 4 x 4 con vaores iniciales unos
print(np.ones((4,4)))

#matriz diagonal con lista como valores de la diagonal principal
print(np.diag((1,2,3,4)))

print(np.identity(5))




[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Operaciones con arreglos

In [21]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(f'{arr1 + arr2 = }')
print(f'{arr1 - arr2 = }')
print(f'{arr1 * arr2 = }')
print(f'{arr1 / arr2 = }')
print(f'{arr1 ** arr2 = }')

arr1 + arr2 = array([5, 7, 9])
arr1 - arr2 = array([-3, -3, -3])
arr1 * arr2 = array([ 4, 10, 18])
arr1 / arr2 = array([0.25, 0.4 , 0.5 ])
arr1 ** arr2 = array([  1,  32, 729])


## Broadcasting

Mecanismo que permite a numpy hacer operaciones con elementos de diferentes formas.
Las dimesniones deben de ser compatibles


ESCALARES
- Realiza la misma operacion a cada elementos del arreglo

In [28]:
import numpy as np

matriz1 = np.array([[1,2], [3,4], [1,2]])
matriz2 = np.array([[3,1]])

print(f'matriz1 * 3 = \n {matriz1 * 3}\n')

print(f'matriz1 + 8 = \n {matriz1 + 8}\n')

print(f'matriz1 / 2 = \n {matriz1 / 2}\n')


matriz1 * 3 = 
 [[ 3  6]
 [ 9 12]
 [ 3  6]]

matriz1 + 8 = 
 [[ 9 10]
 [11 12]
 [ 9 10]]

matriz1 / 2 = 
 [[0.5 1. ]
 [1.5 2. ]
 [0.5 1. ]]



ENTRE ARREGLOS
- Realiza la operación entre cada elementos del arreglo uno por uno

In [35]:
import numpy as np

array2D = np.array([[1,2,3], [4,5,6]])
multi = np.array([1,2,3])

print(f'formas deben de ser compatibles: {array2D.shape} | {multi.shape}')

array2D * multi  #NO ES PRODUCTO MATRICIAL

formas deben de ser compatibles: (2, 3) | (3,)


array([[ 1,  4,  9],
       [ 4, 10, 18]])

Producto matricial

In [36]:
import numpy as np

array2D = np.array([[1,2,3], [4,5,6]])
multi = np.array([1,2,3])

array2D @ multi

array([14, 32])