<a href="https://colab.research.google.com/github/dequiroz/1MTR53_RobIA/blob/main/01_Intro_Python_Robotics/03_Algebra%20Lineal%20con%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://drive.google.com/uc?export=view&id=1FsTa2YzWwxY-HBkd2EOXAlkPJ1zpikWv" alt="drawing" width="150"/>


<p align="center">
<img src="https://drive.google.com/uc?export=view&id=1VBn7nKlruxCPLHH_UuD8B2pkvKP7JLRd" alt="drawing" width="800"/>


</br>

<img src="https://drive.google.com/uc?export=view&id=1tpg1CJh4or-VMrY-Qip25hgedgwy1Y8-" alt="drawing" width="800"/>
</p>


# Computación Científica y Álgebra Lineal con NumPy
* **Responsable del material:** Diego Quiroz Velasquez
* Pontificia Universidad Católica del Perú
* Sección Ingeniería Mecatrónica

---
> **Descripción:**  
> > Este tercer cuaderno interactivo capacita al estudiante en el uso de **NumPy** (Numerical Python). Se aborda la transición desde las listas nativas de Python hacia los arreglos multidimensionales (`ndarray`), fundamentales para implementar algoritmos de cinemática, dinámica y procesamiento de tensores en Inteligencia Artificial. Se enfatiza el álgebra lineal computacional y el paradigma de la **vectorización** para optimizar el rendimiento algorítmico.

<details>
<summary><b> Historial de Versiones del Documento (Hacer clic para desplegar)</b></summary>

<br>

| Versión | Fecha | Autor / Rol | Descripción del Cambio |
| :---: | :---: | :--- | :--- |
| **v1.0** | 29/07/2026 | Diego Quiroz | Creación del módulo de computación científica. Integración de transformaciones homogéneas y cinemática matricial. |

---
</details>
<br>
<img src="https://drive.google.com/uc?export=view&id=1vgFoFHEKMN0WcAFlKS2hPMg2KuBm3sp9" alt="drawing"/>



## 1. Tensores y Eficiencia Computacional: `ndarray` vs. Listas

Las listas de Python almacenan referencias a objetos dispersos en la memoria, lo que las hace flexibles pero ineficientes para el cálculo matemático intensivo.

NumPy resuelve este problema implementando el objeto `ndarray` (N-dimensional array). Estos arreglos están escritos internamente en **C**, almacenan datos del mismo tipo en bloques de memoria contiguos y permiten operaciones matemáticas a nivel de hardware, superando drásticamente la velocidad del Python estándar.

In [1]:
# ==============================================================================
# 1. CREACIÓN DE ARREGLOS Y PERFILES DE TRAYECTORIA
# ==============================================================================
import numpy as np

print("--- 1. Inicialización de Tensores en NumPy ---")

# Conversión de una lista estándar a un arreglo de NumPy
lista_posiciones = [0.0, 1.5, 3.0, 4.5]
vector_posiciones = np.array(lista_posiciones)

print(f"Tipo de objeto: {type(vector_posiciones)}")
print(f"Vector instanciado: {vector_posiciones}")

# NumPy provee funciones optimizadas para generar matrices comunes en control:
# np.zeros(shape) -> Matriz nula
# np.ones(shape) -> Matriz de unos

matriz_nula_3x3 = np.zeros((3, 3))
print(f"\nMatriz de inicialización (3x3):\n{matriz_nula_3x3}")

# np.linspace(inicio, fin, cantidad_muestras)
# Vital para generar perfiles de trayectoria suaves (interpolación).
perfil_tiempo = np.linspace(0.0, 10.0, 5) # 5 puntos equidistantes entre 0 y 10

print(f"\nVector de tiempo discretizado (linspace): {perfil_tiempo} s")

--- 1. Inicialización de Tensores en NumPy ---
Tipo de objeto: <class 'numpy.ndarray'>
Vector instanciado: [0.  1.5 3.  4.5]

Matriz de inicialización (3x3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Vector de tiempo discretizado (linspace): [ 0.   2.5  5.   7.5 10. ] s


## 2. Álgebra Lineal y Transformaciones Geométricas

El análisis matemático en la robótica se basa en el cálculo matricial. Para transformar un punto desde el sistema de coordenadas en el extremo de un manipulador robótico (efector final) al sistema de coordenadas de la base, se utiliza una matriz de transformación homogénea $\mathbf{H}$ de $4 \times 4$.

La relación matemática se define como:
$$ \mathbf{p}_{base} = \mathbf{H} \cdot \mathbf{p}_{efector} $$

En NumPy, el producto matricial (producto punto) se ejecuta mediante la función `np.dot()` o, de forma más elegante y moderna, utilizando el operador `@`.

In [2]:
# ==============================================================================
# 2. OPERACIONES MATRICIALES Y CINEMÁTICA
# ==============================================================================

print("--- 2. Transformación Homogénea 2D ---")

# Definición de un vector de posición homogéneo para el efector [x, y, 1]^T
p_efector = np.array([2.0, 0.0, 1.0])

# Definición de una matriz de transformación H (Rotación de 90° y Traslación en X=5)
# Cos(90) = 0, Sin(90) = 1
matriz_H = np.array([
    [0.0, -1.0, 5.0],
    [1.0,  0.0, 0.0],
    [0.0,  0.0, 1.0]
])

print(f"Vector del efector:\n{p_efector}")
print(f"\nMatriz de Transformación H:\n{matriz_H}")

# Cálculo del producto matricial usando el operador @
p_base = matriz_H @ p_efector

print(f"\nPosición resultante en el marco de la base:\n{p_base}")

# Cálculo de la matriz inversa (para transformar de la base al efector)
matriz_H_inversa = np.linalg.inv(matriz_H)
print(f"\nMatriz Inversa (H^-1):\n{np.round(matriz_H_inversa, 2)}")

--- 2. Transformación Homogénea 2D ---
Vector del efector:
[2. 0. 1.]

Matriz de Transformación H:
[[ 0. -1.  5.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]

Posición resultante en el marco de la base:
[5. 2. 1.]

Matriz Inversa (H^-1):
[[ 0.  1.  0.]
 [-1. -0.  5.]
 [ 0.  0.  1.]]


## 3. Vectorización y Broadcasting (Eliminación de Bucles)

En la programación tradicional en C/C++, aplicar una ganancia a una matriz de datos requiere bucles `for` anidados. En NumPy, este enfoque es un **anti-patrón**.

La **Vectorización** permite aplicar operaciones matemáticas directamente a la matriz completa en una sola instrucción. Esto no solo hace el código más legible, sino que delega el procesamiento al backend en C, optimizando el uso de la CPU.

In [3]:
# ==============================================================================
# 3. VECTORIZACIÓN DE OPERACIONES EN IA Y CONTROL
# ==============================================================================

print("--- 3. Procesamiento Vectorizado ---")

# Señal de error de posición en radianes para 5 articulaciones
errores_rad = np.array([0.1, -0.05, 0.2, 0.0, -0.15])

# En C++, haríamos:
# for(int i=0; i<5; i++) { errores_deg[i] = errores_rad[i] * (180.0 / PI); }

# En NumPy (Vectorización): La operación se aplica a todo el arreglo instantáneamente
errores_grados = errores_rad * (180.0 / np.pi)

print(f"Error en radianes: {errores_rad}")
print(f"Error en grados:   {np.round(errores_grados, 2)}")

print("\n--- Normalización de Dataset (Z-Score) para IA ---")
# En el entrenamiento de redes neuronales, los datos deben normalizarse.
# Z = (X - Media) / Desviación_Estándar

lecturas_sensores = np.array([120, 115, 122, 118, 125, 119])

media = np.mean(lecturas_sensores)
desviacion = np.std(lecturas_sensores)

# Broadcasting: Resta un escalar (media) de un vector entero y divide por otro escalar
datos_normalizados = (lecturas_sensores - media) / desviacion

print(f"Datos crudos: {lecturas_sensores}")
print(f"Datos normalizados (Z-Score): {np.round(datos_normalizados, 3)}")

--- 3. Procesamiento Vectorizado ---
Error en radianes: [ 0.1  -0.05  0.2   0.   -0.15]
Error en grados:   [ 5.73 -2.86 11.46  0.   -8.59]

--- Normalización de Dataset (Z-Score) para IA ---
Datos crudos: [120 115 122 118 125 119]
Datos normalizados (Z-Score): [ 0.053 -1.544  0.692 -0.585  1.65  -0.266]


## 4. Ejercicios Prácticos de Computación Científica

La siguiente sección propone ejercicios para consolidar el pensamiento matricial y la vectorización, competencias ineludibles para la implementación de algoritmos de control moderno e inteligencia artificial.

### Ejercicio 1: Generación de Trayectoria Sinusoidal
**Contexto:** Se requiere generar el movimiento oscilatorio de un efector final para una tarea de soldadura.
**Requerimiento:**
1. Utilice `np.linspace()` para crear un vector de tiempo `t` con **100 muestras**, desde $0.0$ hasta $2\pi$ segundos.
2. Calcule la posición $y$ utilizando la función seno de NumPy (`np.sin()`) aplicada directamente sobre el vector de tiempo (vectorización), con una amplitud de $5.0\text{ cm}$: $y = 5.0 \cdot \sin(t)$.

In [ ]:
# --- INICIO DEL EJERCICIO 1 ---
import numpy as np

# POR HACER 1: Crear el vector de tiempo 't'
t = None

# POR HACER 2: Calcular el vector de posiciones 'y' vectorizadamente
y = None

# --- FIN DEL EJERCICIO 1 ---

# Validación (Impresión de los primeros 5 valores)
if t is not None and y is not None:
    print("Primeros 5 instantes de tiempo:", np.round(t[:5], 3))
    print("Primeras 5 posiciones en Y (cm):", np.round(y[:5], 3))

### Ejercicio 2: Producto Cruz y Momento de Fuerza
**Contexto:** En el análisis estático de un manipulador, el momento de fuerza (torque) $\boldsymbol{\tau}$ generado por una fuerza $\mathbf{F}$ aplicada a una distancia $\mathbf{r}$ del origen se calcula mediante el producto cruz vectorial:
$$ \boldsymbol{\tau} = \mathbf{r} \times \mathbf{F} $$
**Requerimiento:**
1. Dados los vectores espaciales $\mathbf{r} = [1.5, 0.0, 0.0]\text{ m}$ y $\mathbf{F} = [0.0, 0.0, -10.0]\text{ N}$.
2. Utilice la función `np.cross()` para calcular el vector de torque $\boldsymbol{\tau}$.

In [ ]:
# --- INICIO DEL EJERCICIO 2 ---

# POR HACER 1: Definir los vectores r y F como arreglos de NumPy
vector_r = np.array([])
vector_F = np.array([])

# POR HACER 2: Calcular el producto cruz
vector_torque = None

# --- FIN DEL EJERCICIO 2 ---

print(f"Vector Torque (Nx, Ny, Nz): {vector_torque} Nm")

### Ejercicio 3: Cálculo Vectorizado de Error (MSE)
**Contexto:** En la evaluación de modelos de Inteligencia Artificial y controladores PID, el Error Cuadrático Medio (MSE - *Mean Squared Error*) es la métrica de rendimiento estándar. Se define como el promedio de los cuadrados de los errores entre la señal de referencia y la señal medida.
**Requerimiento:**
1. Dados dos arreglos NumPy: `referencia` y `medicion`.
2. Calcule el vector de error: `error = referencia - medicion`.
3. Eleve el vector de error al cuadrado utilizando el operador de potencia de Python (`** 2`) aprovechando la vectorización de NumPy.
4. Calcule el promedio del error cuadrático utilizando `np.mean()`.

In [ ]:
# --- INICIO DEL EJERCICIO 3 ---

referencia = np.array([10.0, 10.0, 10.0, 10.0])
medicion = np.array([9.5, 9.8, 10.1, 10.0])

# POR HACER 1: Calcular el vector de diferencia
vector_error = None

# POR HACER 2: Elevar el vector de error al cuadrado
error_cuadratico = None

# POR HACER 3: Calcular el promedio (MSE)
mse = 0.0

# --- FIN DEL EJERCICIO 3 ---

print(f"Señal de Referencia: {referencia}")
print(f"Señal Medida:        {medicion}")
print(f"Error Cuadrático Medio (MSE): {mse:.4f}")